steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
<<<<<<< HEAD
  args: ['build', '-t', | 'us-west1-docker.pkg.dev/clever-guard-407300/mydockerrepo/cloudbuildimage', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-west1-docker.pkg.dev/clever-guard-407300/mydockerrepo/cloudbuildimage']

# Store images in Artifact Registry
images:
  - us-west1-docker.pkg.dev/clever-guard-407300/mydockerrepo/cloudbuildimage
=======
  args: ['build', '-t', | 'us-west1-docker.pkg.dev/clever-guard-407300/mydockerrepo/myimage:${SHORT_SHA}', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-west1-docker.pkg.dev/clever-guard-407300/mydockerrepo/myimage:${SHORT-SHA}']

# Store images in Artifact Registry
images:
  - us-west1-docker.pkg.dev/clever-guard-407300/mydockerrepo/myimage:${SHORT-SHA}
>>>>>>> 160d95905c2e1a0de9f7f0b6b09f4489803479f4
  
