steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west1-docker.pkg.dev/clever-guard-407300/mydockerrepo/cloudbuildimage', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west1-docker.pkg.dev/clever-guard-407300/mydockerrepo/cloudbuildimage']

    - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'cloudrun', '--image=us-wst1-docker.pkg.dev/clever-guard-407300/mydockerrepo/cloudbuildimage', '--region=us-west1']

# Stored images in Artifact Registry
images:
  - 'us-west1-docker.pkg.dev/clever-guard-407300/mydockerrepo/cloudbuildimage'

